repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: check-apt-in-app-dockerfile
        name: Check for apt usage in App Dockerfile
        entry: bash -c '! grep -Ei "apt-get|apt install" Dockerfile'
        language: system
        files: ^Dockerfile$
        pass_filenames: false
        message: "Error: Do not use 'apt' in the main Dockerfile. Please update Dockerfile.base instead to include new system dependencies."

      - id: custom-bandit
        name: Security check (Bandit)
        entry: python3 scripts/security_check.py
        language: system
        pass_filenames: false
        always_run: true

      - id: meaningless-comments
        name: Check for meaningless comments
        entry: python3 scripts/check_comments.py
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
